### PR TITLE
Create README.md

### LINKED ISSUE #7: Add README.md
This project needs a README.md - I'll submit a PR shortly.

### PR DESCRIPTION
**Pull request by david-poindexter**
This was essentially copied from the CodePlex archive and updated to accommodate GitHub markdown. Resolves #7

### CODE REVIEW

**Comment by david-poindexter** [comment]
He @mathisjay - just checking in on the status of this pull request.  I'd like to make some more significant contributions, but I would like to know this project is being maintained before investing the time and energy.  Thanks, and I look forward to hearing from you.

**Comment by X3Technology** [comment]
Hey thanks!  For some reason, i never got the notification.  I will review asap.



Sent via the Samsung Galaxy S7 edge, an AT&T 4G LTE smartphone


-------- Original message --------

**Comment by david-poindexter** [comment]
No worries.  Thanks @mathisjay.  Just in case you didn't receive all the other notifications, there are quite a few [Issues](https://github.com/mathisjay/X3.DnnUrlManagement/issues) posted as well from us and @hismightiness.  None of them have been responded to yet.

**Comment by david-poindexter** [comment]
@mathisjay any chance of getting this PR merged as well?

**Comment by david-poindexter** [comment]
Friendly bump...

**Comment by david-poindexter** [comment]
image

**Comment by david-poindexter** [comment]
image

**Comment by rodrigoratan** [comment]
@david-poindexter Was it transferred to https://github.com/mathisjay/X3.AdvancedUrlManagement ?

**Comment by david-poindexter** [comment]
🤷

**Comment by WillStrohl** [comment]
☹️

**Comment by david-poindexter** [comment]
Giving up and closing this PR...

**Pull request closed without merging**
